# -*- coding: utf-8 -*-
"""11_8_sep_TEXT_classification_JSON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfY7e2hE2XGz3XXHkxtJCNc-Yq9iJoaX
"""

import json
import pandas as pd
import numpy as np

import torch
from transformers import BertTokenizer, BertModel

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

from tqdm import tqdm

import time
#from tqdm import tqdm

# Wraply
for i in tqdm(range(100)):
    time.sleep(0.05)  # Simulate processing time

!pwd

!dir

file_path = "/sarcasm.json"

with open(file_path, "r") as f:
    data = json.load(f)

data

df = pd.DataFrame(data)
df

df = df[["headline", "is_sarcastic"]]

df.head()

df.shape

X = df["headline"].values
y = df["is_sarcastic"].values

X

y

# stratify=y ---- in test it will balance the classess

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

X_train.shape

X_test.shape

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")

model.eval()

for i in range(0,100,16):
  print(i)

def get_bert_embeddings(texts, batch_size=16):
    embeddings = []

    for i in tqdm(range(0, len(texts), batch_size)):
        batch_texts = texts[i:i+batch_size] #16 text

        encoded = tokenizer(
            list(batch_texts),
            padding=True,
            truncation=True,
            max_length=64,
            return_tensors="pt"
        )

        with torch.no_grad():
            outputs = model(**encoded)

        # CLS token embedding
        cls_embeddings = outputs.last_hidden_state[:, 0, :]
        embeddings.append(cls_embeddings.numpy())

    return np.vstack(embeddings)

X_train_emb = get_bert_embeddings(X_train)
X_test_emb = get_bert_embeddings(X_test)

X_train_emb.shape

X_test_emb.shape

clf = LogisticRegression(
    max_iter=1000,
    solver="lbfgs"
)

clf.fit(X_train_emb, y_train)

import joblib

joblib.dump(clf, "sarcasm_classifier.pkl")

print("Model saved successfully!")

y_pred = clf.predict(X_test_emb)

y_pred

y_test

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

def predict_sarcasm(text):
    emb = get_bert_embeddings([text])
    pred = clf.predict(emb)[0]
    return "Sarcastic" if pred == 1 else "Not Sarcastic"

predict_sarcasm("")Oh great, another Monday morning meeting

predict_sarcasm("How are you ?")

predict_sarcasm("Nation thrilled to pay higher taxes again")

predict_sarcasm("Man excited to spend weekend fixing printer")

